//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViajecitosSAClienteEscritorio.CondorService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vuelo", Namespace="http://aerocondor.com/")]
    [System.SerializableAttribute()]
    public partial class Vuelo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadDestinoField;
        
        private decimal ValorField;
        
        private System.DateTime HoraSalidaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CiudadOrigen {
            get {
                return this.CiudadOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadOrigenField, value) != true)) {
                    this.CiudadOrigenField = value;
                    this.RaisePropertyChanged("CiudadOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CiudadDestino {
            get {
                return this.CiudadDestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadDestinoField, value) != true)) {
                    this.CiudadDestinoField = value;
                    this.RaisePropertyChanged("CiudadDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime HoraSalida {
            get {
                return this.HoraSalidaField;
            }
            set {
                if ((this.HoraSalidaField.Equals(value) != true)) {
                    this.HoraSalidaField = value;
                    this.RaisePropertyChanged("HoraSalida");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Factura", Namespace="http://aerocondor.com/")]
    [System.SerializableAttribute()]
    public partial class Factura : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private int UsuarioIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioField;
        
        private int EdadUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NacionalidadUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadDestinoField;
        
        private System.DateTime HoraSalidaField;
        
        private int CantidadField;
        
        private decimal PrecioUnitarioField;
        
        private decimal PrecioTotalField;
        
        private System.DateTime FechaEmisionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UsuarioId {
            get {
                return this.UsuarioIdField;
            }
            set {
                if ((this.UsuarioIdField.Equals(value) != true)) {
                    this.UsuarioIdField = value;
                    this.RaisePropertyChanged("UsuarioId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NombreUsuario {
            get {
                return this.NombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioField, value) != true)) {
                    this.NombreUsuarioField = value;
                    this.RaisePropertyChanged("NombreUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int EdadUsuario {
            get {
                return this.EdadUsuarioField;
            }
            set {
                if ((this.EdadUsuarioField.Equals(value) != true)) {
                    this.EdadUsuarioField = value;
                    this.RaisePropertyChanged("EdadUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string NacionalidadUsuario {
            get {
                return this.NacionalidadUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NacionalidadUsuarioField, value) != true)) {
                    this.NacionalidadUsuarioField = value;
                    this.RaisePropertyChanged("NacionalidadUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CiudadOrigen {
            get {
                return this.CiudadOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadOrigenField, value) != true)) {
                    this.CiudadOrigenField = value;
                    this.RaisePropertyChanged("CiudadOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CiudadDestino {
            get {
                return this.CiudadDestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadDestinoField, value) != true)) {
                    this.CiudadDestinoField = value;
                    this.RaisePropertyChanged("CiudadDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime HoraSalida {
            get {
                return this.HoraSalidaField;
            }
            set {
                if ((this.HoraSalidaField.Equals(value) != true)) {
                    this.HoraSalidaField = value;
                    this.RaisePropertyChanged("HoraSalida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public decimal PrecioUnitario {
            get {
                return this.PrecioUnitarioField;
            }
            set {
                if ((this.PrecioUnitarioField.Equals(value) != true)) {
                    this.PrecioUnitarioField = value;
                    this.RaisePropertyChanged("PrecioUnitario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public decimal PrecioTotal {
            get {
                return this.PrecioTotalField;
            }
            set {
                if ((this.PrecioTotalField.Equals(value) != true)) {
                    this.PrecioTotalField = value;
                    this.RaisePropertyChanged("PrecioTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.DateTime FechaEmision {
            get {
                return this.FechaEmisionField;
            }
            set {
                if ((this.FechaEmisionField.Equals(value) != true)) {
                    this.FechaEmisionField = value;
                    this.RaisePropertyChanged("FechaEmision");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://aerocondor.com/", ConfigurationName="CondorService.CondorServiceSoap")]
    public interface CondorServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento origen del espacio de nombres http://aerocondor.com/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ObtenerVuelos", ReplyAction="*")]
        ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosResponse ObtenerVuelos(ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ObtenerVuelos", ReplyAction="*")]
        System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosResponse> ObtenerVuelosAsync(ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ComprarVueloResult del espacio de nombres http://aerocondor.com/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ComprarVuelo", ReplyAction="*")]
        ViajecitosSAClienteEscritorio.CondorService.ComprarVueloResponse ComprarVuelo(ViajecitosSAClienteEscritorio.CondorService.ComprarVueloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ComprarVuelo", ReplyAction="*")]
        System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ComprarVueloResponse> ComprarVueloAsync(ViajecitosSAClienteEscritorio.CondorService.ComprarVueloRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerVueloPorIdResult del espacio de nombres http://aerocondor.com/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ObtenerVueloPorId", ReplyAction="*")]
        ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdResponse ObtenerVueloPorId(ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ObtenerVueloPorId", ReplyAction="*")]
        System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdResponse> ObtenerVueloPorIdAsync(ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento tipoFiltro del espacio de nombres http://aerocondor.com/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ObtenerVuelosPorFiltro", ReplyAction="*")]
        ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroResponse ObtenerVuelosPorFiltro(ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ObtenerVuelosPorFiltro", ReplyAction="*")]
        System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroResponse> ObtenerVuelosPorFiltroAsync(ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://aerocondor.com/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/Login", ReplyAction="*")]
        ViajecitosSAClienteEscritorio.CondorService.LoginResponse Login(ViajecitosSAClienteEscritorio.CondorService.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.LoginResponse> LoginAsync(ViajecitosSAClienteEscritorio.CondorService.LoginRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ComprarVueloConCantidadResult del espacio de nombres http://aerocondor.com/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ComprarVueloConCantidad", ReplyAction="*")]
        ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadResponse ComprarVueloConCantidad(ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ComprarVueloConCantidad", ReplyAction="*")]
        System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadResponse> ComprarVueloConCantidadAsync(ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerFacturaPorIdResult del espacio de nombres http://aerocondor.com/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ObtenerFacturaPorId", ReplyAction="*")]
        ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdResponse ObtenerFacturaPorId(ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ObtenerFacturaPorId", ReplyAction="*")]
        System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdResponse> ObtenerFacturaPorIdAsync(ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerVuelosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerVuelos", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosRequestBody Body;
        
        public ObtenerVuelosRequest() {
        }
        
        public ObtenerVuelosRequest(ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ObtenerVuelosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string origen;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string destino;
        
        public ObtenerVuelosRequestBody() {
        }
        
        public ObtenerVuelosRequestBody(string origen, string destino) {
            this.origen = origen;
            this.destino = destino;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerVuelosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerVuelosResponse", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosResponseBody Body;
        
        public ObtenerVuelosResponse() {
        }
        
        public ObtenerVuelosResponse(ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ObtenerVuelosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.Vuelo[] ObtenerVuelosResult;
        
        public ObtenerVuelosResponseBody() {
        }
        
        public ObtenerVuelosResponseBody(ViajecitosSAClienteEscritorio.CondorService.Vuelo[] ObtenerVuelosResult) {
            this.ObtenerVuelosResult = ObtenerVuelosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComprarVueloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComprarVuelo", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.ComprarVueloRequestBody Body;
        
        public ComprarVueloRequest() {
        }
        
        public ComprarVueloRequest(ViajecitosSAClienteEscritorio.CondorService.ComprarVueloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ComprarVueloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int vueloId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int usuarioId;
        
        public ComprarVueloRequestBody() {
        }
        
        public ComprarVueloRequestBody(int vueloId, int usuarioId) {
            this.vueloId = vueloId;
            this.usuarioId = usuarioId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComprarVueloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComprarVueloResponse", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.ComprarVueloResponseBody Body;
        
        public ComprarVueloResponse() {
        }
        
        public ComprarVueloResponse(ViajecitosSAClienteEscritorio.CondorService.ComprarVueloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ComprarVueloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ComprarVueloResult;
        
        public ComprarVueloResponseBody() {
        }
        
        public ComprarVueloResponseBody(string ComprarVueloResult) {
            this.ComprarVueloResult = ComprarVueloResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerVueloPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerVueloPorId", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdRequestBody Body;
        
        public ObtenerVueloPorIdRequest() {
        }
        
        public ObtenerVueloPorIdRequest(ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ObtenerVueloPorIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public ObtenerVueloPorIdRequestBody() {
        }
        
        public ObtenerVueloPorIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerVueloPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerVueloPorIdResponse", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdResponseBody Body;
        
        public ObtenerVueloPorIdResponse() {
        }
        
        public ObtenerVueloPorIdResponse(ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ObtenerVueloPorIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.Vuelo ObtenerVueloPorIdResult;
        
        public ObtenerVueloPorIdResponseBody() {
        }
        
        public ObtenerVueloPorIdResponseBody(ViajecitosSAClienteEscritorio.CondorService.Vuelo ObtenerVueloPorIdResult) {
            this.ObtenerVueloPorIdResult = ObtenerVueloPorIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerVuelosPorFiltroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerVuelosPorFiltro", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroRequestBody Body;
        
        public ObtenerVuelosPorFiltroRequest() {
        }
        
        public ObtenerVuelosPorFiltroRequest(ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ObtenerVuelosPorFiltroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tipoFiltro;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string valor;
        
        public ObtenerVuelosPorFiltroRequestBody() {
        }
        
        public ObtenerVuelosPorFiltroRequestBody(string tipoFiltro, string valor) {
            this.tipoFiltro = tipoFiltro;
            this.valor = valor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerVuelosPorFiltroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerVuelosPorFiltroResponse", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroResponseBody Body;
        
        public ObtenerVuelosPorFiltroResponse() {
        }
        
        public ObtenerVuelosPorFiltroResponse(ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ObtenerVuelosPorFiltroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.Vuelo[] ObtenerVuelosPorFiltroResult;
        
        public ObtenerVuelosPorFiltroResponseBody() {
        }
        
        public ObtenerVuelosPorFiltroResponseBody(ViajecitosSAClienteEscritorio.CondorService.Vuelo[] ObtenerVuelosPorFiltroResult) {
            this.ObtenerVuelosPorFiltroResult = ObtenerVuelosPorFiltroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(ViajecitosSAClienteEscritorio.CondorService.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(ViajecitosSAClienteEscritorio.CondorService.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComprarVueloConCantidadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComprarVueloConCantidad", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadRequestBody Body;
        
        public ComprarVueloConCantidadRequest() {
        }
        
        public ComprarVueloConCantidadRequest(ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ComprarVueloConCantidadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int vueloId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int usuarioId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int cantidad;
        
        public ComprarVueloConCantidadRequestBody() {
        }
        
        public ComprarVueloConCantidadRequestBody(int vueloId, int usuarioId, int cantidad) {
            this.vueloId = vueloId;
            this.usuarioId = usuarioId;
            this.cantidad = cantidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComprarVueloConCantidadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComprarVueloConCantidadResponse", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadResponseBody Body;
        
        public ComprarVueloConCantidadResponse() {
        }
        
        public ComprarVueloConCantidadResponse(ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ComprarVueloConCantidadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ComprarVueloConCantidadResult;
        
        public ComprarVueloConCantidadResponseBody() {
        }
        
        public ComprarVueloConCantidadResponseBody(string ComprarVueloConCantidadResult) {
            this.ComprarVueloConCantidadResult = ComprarVueloConCantidadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerFacturaPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerFacturaPorId", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdRequestBody Body;
        
        public ObtenerFacturaPorIdRequest() {
        }
        
        public ObtenerFacturaPorIdRequest(ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ObtenerFacturaPorIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int facturaId;
        
        public ObtenerFacturaPorIdRequestBody() {
        }
        
        public ObtenerFacturaPorIdRequestBody(int facturaId) {
            this.facturaId = facturaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerFacturaPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerFacturaPorIdResponse", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdResponseBody Body;
        
        public ObtenerFacturaPorIdResponse() {
        }
        
        public ObtenerFacturaPorIdResponse(ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ObtenerFacturaPorIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.Factura ObtenerFacturaPorIdResult;
        
        public ObtenerFacturaPorIdResponseBody() {
        }
        
        public ObtenerFacturaPorIdResponseBody(ViajecitosSAClienteEscritorio.CondorService.Factura ObtenerFacturaPorIdResult) {
            this.ObtenerFacturaPorIdResult = ObtenerFacturaPorIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CondorServiceSoapChannel : ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CondorServiceSoapClient : System.ServiceModel.ClientBase<ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap>, ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap {
        
        public CondorServiceSoapClient() {
        }
        
        public CondorServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CondorServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CondorServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CondorServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosResponse ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap.ObtenerVuelos(ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosRequest request) {
            return base.Channel.ObtenerVuelos(request);
        }
        
        public ViajecitosSAClienteEscritorio.CondorService.Vuelo[] ObtenerVuelos(string origen, string destino) {
            ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosRequest inValue = new ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosRequest();
            inValue.Body = new ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosRequestBody();
            inValue.Body.origen = origen;
            inValue.Body.destino = destino;
            ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosResponse retVal = ((ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap)(this)).ObtenerVuelos(inValue);
            return retVal.Body.ObtenerVuelosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosResponse> ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap.ObtenerVuelosAsync(ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosRequest request) {
            return base.Channel.ObtenerVuelosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosResponse> ObtenerVuelosAsync(string origen, string destino) {
            ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosRequest inValue = new ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosRequest();
            inValue.Body = new ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosRequestBody();
            inValue.Body.origen = origen;
            inValue.Body.destino = destino;
            return ((ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap)(this)).ObtenerVuelosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ViajecitosSAClienteEscritorio.CondorService.ComprarVueloResponse ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap.ComprarVuelo(ViajecitosSAClienteEscritorio.CondorService.ComprarVueloRequest request) {
            return base.Channel.ComprarVuelo(request);
        }
        
        public string ComprarVuelo(int vueloId, int usuarioId) {
            ViajecitosSAClienteEscritorio.CondorService.ComprarVueloRequest inValue = new ViajecitosSAClienteEscritorio.CondorService.ComprarVueloRequest();
            inValue.Body = new ViajecitosSAClienteEscritorio.CondorService.ComprarVueloRequestBody();
            inValue.Body.vueloId = vueloId;
            inValue.Body.usuarioId = usuarioId;
            ViajecitosSAClienteEscritorio.CondorService.ComprarVueloResponse retVal = ((ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap)(this)).ComprarVuelo(inValue);
            return retVal.Body.ComprarVueloResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ComprarVueloResponse> ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap.ComprarVueloAsync(ViajecitosSAClienteEscritorio.CondorService.ComprarVueloRequest request) {
            return base.Channel.ComprarVueloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ComprarVueloResponse> ComprarVueloAsync(int vueloId, int usuarioId) {
            ViajecitosSAClienteEscritorio.CondorService.ComprarVueloRequest inValue = new ViajecitosSAClienteEscritorio.CondorService.ComprarVueloRequest();
            inValue.Body = new ViajecitosSAClienteEscritorio.CondorService.ComprarVueloRequestBody();
            inValue.Body.vueloId = vueloId;
            inValue.Body.usuarioId = usuarioId;
            return ((ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap)(this)).ComprarVueloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdResponse ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap.ObtenerVueloPorId(ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdRequest request) {
            return base.Channel.ObtenerVueloPorId(request);
        }
        
        public ViajecitosSAClienteEscritorio.CondorService.Vuelo ObtenerVueloPorId(int id) {
            ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdRequest inValue = new ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdRequest();
            inValue.Body = new ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdRequestBody();
            inValue.Body.id = id;
            ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdResponse retVal = ((ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap)(this)).ObtenerVueloPorId(inValue);
            return retVal.Body.ObtenerVueloPorIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdResponse> ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap.ObtenerVueloPorIdAsync(ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdRequest request) {
            return base.Channel.ObtenerVueloPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdResponse> ObtenerVueloPorIdAsync(int id) {
            ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdRequest inValue = new ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdRequest();
            inValue.Body = new ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdRequestBody();
            inValue.Body.id = id;
            return ((ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap)(this)).ObtenerVueloPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroResponse ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap.ObtenerVuelosPorFiltro(ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroRequest request) {
            return base.Channel.ObtenerVuelosPorFiltro(request);
        }
        
        public ViajecitosSAClienteEscritorio.CondorService.Vuelo[] ObtenerVuelosPorFiltro(string tipoFiltro, string valor) {
            ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroRequest inValue = new ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroRequest();
            inValue.Body = new ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroRequestBody();
            inValue.Body.tipoFiltro = tipoFiltro;
            inValue.Body.valor = valor;
            ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroResponse retVal = ((ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap)(this)).ObtenerVuelosPorFiltro(inValue);
            return retVal.Body.ObtenerVuelosPorFiltroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroResponse> ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap.ObtenerVuelosPorFiltroAsync(ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroRequest request) {
            return base.Channel.ObtenerVuelosPorFiltroAsync(request);
        }
        
        public System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroResponse> ObtenerVuelosPorFiltroAsync(string tipoFiltro, string valor) {
            ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroRequest inValue = new ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroRequest();
            inValue.Body = new ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroRequestBody();
            inValue.Body.tipoFiltro = tipoFiltro;
            inValue.Body.valor = valor;
            return ((ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap)(this)).ObtenerVuelosPorFiltroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ViajecitosSAClienteEscritorio.CondorService.LoginResponse ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap.Login(ViajecitosSAClienteEscritorio.CondorService.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string username, string password) {
            ViajecitosSAClienteEscritorio.CondorService.LoginRequest inValue = new ViajecitosSAClienteEscritorio.CondorService.LoginRequest();
            inValue.Body = new ViajecitosSAClienteEscritorio.CondorService.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            ViajecitosSAClienteEscritorio.CondorService.LoginResponse retVal = ((ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.LoginResponse> ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap.LoginAsync(ViajecitosSAClienteEscritorio.CondorService.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.LoginResponse> LoginAsync(string username, string password) {
            ViajecitosSAClienteEscritorio.CondorService.LoginRequest inValue = new ViajecitosSAClienteEscritorio.CondorService.LoginRequest();
            inValue.Body = new ViajecitosSAClienteEscritorio.CondorService.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadResponse ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap.ComprarVueloConCantidad(ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadRequest request) {
            return base.Channel.ComprarVueloConCantidad(request);
        }
        
        public string ComprarVueloConCantidad(int vueloId, int usuarioId, int cantidad) {
            ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadRequest inValue = new ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadRequest();
            inValue.Body = new ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadRequestBody();
            inValue.Body.vueloId = vueloId;
            inValue.Body.usuarioId = usuarioId;
            inValue.Body.cantidad = cantidad;
            ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadResponse retVal = ((ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap)(this)).ComprarVueloConCantidad(inValue);
            return retVal.Body.ComprarVueloConCantidadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadResponse> ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap.ComprarVueloConCantidadAsync(ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadRequest request) {
            return base.Channel.ComprarVueloConCantidadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadResponse> ComprarVueloConCantidadAsync(int vueloId, int usuarioId, int cantidad) {
            ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadRequest inValue = new ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadRequest();
            inValue.Body = new ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadRequestBody();
            inValue.Body.vueloId = vueloId;
            inValue.Body.usuarioId = usuarioId;
            inValue.Body.cantidad = cantidad;
            return ((ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap)(this)).ComprarVueloConCantidadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdResponse ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap.ObtenerFacturaPorId(ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdRequest request) {
            return base.Channel.ObtenerFacturaPorId(request);
        }
        
        public ViajecitosSAClienteEscritorio.CondorService.Factura ObtenerFacturaPorId(int facturaId) {
            ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdRequest inValue = new ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdRequest();
            inValue.Body = new ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdRequestBody();
            inValue.Body.facturaId = facturaId;
            ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdResponse retVal = ((ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap)(this)).ObtenerFacturaPorId(inValue);
            return retVal.Body.ObtenerFacturaPorIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdResponse> ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap.ObtenerFacturaPorIdAsync(ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdRequest request) {
            return base.Channel.ObtenerFacturaPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdResponse> ObtenerFacturaPorIdAsync(int facturaId) {
            ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdRequest inValue = new ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdRequest();
            inValue.Body = new ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdRequestBody();
            inValue.Body.facturaId = facturaId;
            return ((ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap)(this)).ObtenerFacturaPorIdAsync(inValue);
        }
    }
}
